kind: Service
apiVersion: v1
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  selector:
    app: consumer
  ports:
  - protocol: TCP
    port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "processor"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: consumer
        image: nhatthai/dotnet5-consumer.api
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /consumer
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        ports:
        - containerPort: 80
